### ISSUE TITLE
namespace error bug

### ISSUE THREAD

**Issue by ndj888** [aaronpk/php-multipart-encoder#3]
When I run phpunit , it not working. If remove the package , it working. Maybe some questions in package about namespace. Want package to work , thank.
##info
Fatal error: Cannot declare class p3k\Multipart, because the name is already in use in /opt/project/vendor/p3k/multipart/src/p3k/Multipart.php on line 4
                                                                          
  [think\exception\ErrorException]                                        
  Cannot declare class p3k\Multipart, because the name is already in use  
                                                                          

Exception trace:
 () at /opt/project/vendor/p3k/multipart/src/p3k/Multipart.php:4
 think\Error::appShutdown() at n/a:n/a
###

my composer.json

`{
    "name": "topthink/think",
    "description": "the new thinkphp framework",
    "type": "project",
    "keywords": [
        "framework",
        "thinkphp",
        "ORM"
    ],
    "homepage": "http://thinkphp.cn/",
    "license": "Apache-2.0",
    "authors": [
        {
            "name": "liu21st",
            "email": "liu21st@gmail.com"
        }
    ],
    "require": {
        "php": ">=5.4.0",
        "topthink/framework": "5.0",
        "topthink/think-captcha": "v1.0.7",
        "topthink/think-mongo": "v1.6",
        "topthink/think-image": "v1.0.7",
        "topthink/think-testing": "v1.0.6",
        "topthink/think-sae": "v1.1",
        "topthink/think-queue": "v1.1.3",
        "topthink/think-migration": "v1.1.1",
        "doctrine/orm": "^v2.5.6",
        "phpexcel/phpexcel": "v1.7.7",
        "php-curl-class/php-curl-class": "^7.2.0",
        "p3k/multipart": "0.2.0"
    },
    "extra": {
        "think-path": "thinkphp"
    },
    "config": {
        "preferred-install": "dist"
    },
    "autoload" :{
        "psr-4" :{
            "imsdk\\" :"vendor/imsdk/",
            "ext\\": "ext/",
            "crontab\\": "crontab/",
            "Predis\\" : "vendor/predis/",
            "Entitys\\": "entitys/",
            "tests\\": "tests/"
        },
        "psr-0": {
            "Auto": "src/"
        }
    }
}
`

**Comment by ndj888** [comment]
If the bug  is't solved , I having to copy the file in my project dir , doing requrie use the package.

**Comment by aaronpk** [comment]
I'm having trouble re-creating this error. Installing a new project with the `composer.json` you provided doesn't work, I get errors about missing classes in the `think` namespace.
